messages:
  only_for_players: "&cТолько для игроков!"
  no_args: "&cНедостаточно аргументов!"
  cooldown: "&cСлишком часто! Попробуйте позже!"
  no_permissions: "&cНедостаточно прав!"
  player_not_found: "&cИгрок %player% не найден!"
  inventorygui_not_found: "Иневнтарь %namespace% не найден!"
redis:
  enable: false
  host: "127.0.0.1"
  port: 6379
  user: "root"
  password: "password"