messages:
  only_for_players: "&cТолько для игроков!"
  no_args: "&cНедостаточно аргументов!"
  no_permissions: "&cНедостаточно прав!"
  player_not_found: "&cИгрок %player% не найден!"
  inventorygui_not_found: "Иневнтарь %namespace% не найден!"
redis:
  host: "172.18.0.1"
  port: 6379
  user: "whitebeef"
  password: "P@55w0rd"