name: SimpleCI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build project
      run: ./gradlew build


  sonar-check:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: SonarCheck
      run: ./gradlew sonar
